### ISSUE TITLE
?????? WHAT IS SOYINO STATS AND HOW DO WE USE IT ??????????????

### ISSUE THREAD

**Issue by IdotMaster1** [Bilaboz/duino-stats#1]
USE COMMON BUNKER INNOVATION TOOLS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! REJECT SOYTHON!!!!!!!!!!!!!!!!!! REJECT CENTRILSATION !!!!!!!!!!!!!!!!!!!!!!!!!!1

**Comment by phrl42** [comment]
stop
