### ISSUE TITLE
@Bilaboz You should read this:

### ISSUE THREAD

**Issue by IdotMaster1** [Bilaboz/duino-stats#4]
https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Access-Deprecation-for-Verified-Bots

WHAT WILL AN UNAPPROVED BOT LOSE ACCESS TO?
If your bot or app is not approved for message content, the following fields of the message object in Gateway and API payloads will be empty—either an empty string or empty array, depending on the data type—when you receive a message:

content
embeds
attachments
components

Will this effect Duino-Stats?

**Comment by primitt** [comment]
https://i.imgur.com/BOtLxO4.png

**Comment by primitt** [comment]
[https://i.imgur.com/BOtLxO4.png]()

**Comment by primitt** [comment]
uggg no embed

**Comment by Bilaboz** [comment]
> https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Access-Deprecation-for-Verified-Bots
> 
> WHAT WILL AN UNAPPROVED BOT LOSE ACCESS TO? If your bot or app is not approved for message content, the following fields of the message object in Gateway and API payloads will be empty—either an empty string or empty array, depending on the data type—when you receive a message:
> 
> content embeds attachments components
> 
> Will this effect Duino-Stats?

It shouldn't affect duino-stats since it's not in more than 100 servers, as @primitt screenshot shows
