### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TimyIsCool** [Bilaboz/duino-stats#7]
![image](https://user-images.githubusercontent.com/74112751/151207328-dc0fe5d2-3176-494e-8d36-6c23c583bf1b.png)
What should I do?

**Comment by ivanrpz** [comment]
Check that folder /commands is accesible by the file.

Also try to make a console.log(pull) after line 70 to know more info about this error

**Comment by Bilaboz** [comment]
Hello, check what @ivanrpz said and tell us the output.
Also, did you added a command or modified one?
